# Generated by Django 4.2 on 2023-04-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='/home', max_length=255),
        ),
    ]
