# Generated by Django 4.2 on 2023-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0003_rename_amount_convertedcurrency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedcurrency',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
