# Generated by Django 4.2 on 2023-04-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(blank=True, choices=[('gbp', 'GBP'), ('usd', 'USD'), ('eur', 'EUR')], max_length=4),
        ),
    ]
