# Generated by Django 4.2 on 2023-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_transaction_currency_payrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrequest',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
